### ISSUE TITLE
Latest version is incompatible with dbt-core 1.5.0

### ISSUE THREAD

**Issue by millin** [tomasfarias/airflow-dbt-python#117]
```python
from dbt.config.runtime import UnsetProfileConfig

ImportError: cannot import name 'UnsetProfileConfig' from 'dbt.config.runtime' (/usr/local/airflow/.local/lib/python3.10/site-packages/dbt/config/runtime.py)
```

**Comment by tomasfarias** [comment]
Likely latest release has changed an `import` path. I can take a look at this later today.

**Comment by tomasfarias** [comment]
Update: dbt-core doesn't use `UnsetProfileConfig` anymore. A more intuitive check for `DepsTask` or `CleanTask` should achieve the same result and be compatible with 1.5. If my PR tests are all green, I'll deploy v1.0.6 with the fix.

**Comment by tomasfarias** [comment]
Unfortunately, `UnsetProfileConfig` wasn't the only thing removed in dbt-core 1.5: apparently `ParseTask` is no more, and a lot of setup functions changed their signature. I'm pushing some changes to maintain backwards compatibility as I do not wish to drop support for dbt 1.4 just yet. However, these changes will require testing, so it's likely this fix will not be as quick as expected. In the meantime, stick to dbt-core==1.4.5.

We don't have a policy on dbt supported versions, so as long as it's not much of a hassle, I'll try to support all >= 1.0.0.

**Comment by samLozier** [comment]
@tomasfarias This is also blocking my team. Is there anything we could do that would help you get these changes across the line?

**Comment by tomasfarias** [comment]
Hey all, I was on vacation throughout June, now getting back on this topic.

Unfortunately, dbt v1.5 completed a massive move to click for all the CLI internals. airflow-dbt-python was built by mocking or re-implementing the initialization steps executed by the dbt CLI, and those have now been completely refactored in dbt v1.5.

In an ideal world, dbt would provide a Python library that we can import directly, instead of being always tied to the CLI. [That doesn't seem to be the direction dbt is taking](https://docs.getdbt.com/reference/programmatic-invocations), so I'm not keeping up my hopes for this.

In the long term, it would be amazing if we could fork dbt-core, strip out all the CLI, tracking, event, logging, and other auxiliary code, and publish a `dbt-lib` package that we can then use. Ultimately, airflow-dbt-python should just be focused on the added Airflow functionality, not on dealing with the dbt CLI, and its annoying to have to interrupt feature development because the latest dbt version broke us in a way we ultimately shouldn't care about.

This is not an easy task though.

From my end, I'm continuing work on #118. Already managed to get all flags to initialize (not in a pretty way, I'm trying to get this working first), and removed some deprecated classes.

The problem I'm facing right now is that the database connection is failing in all the tests. This leads me to believe dbt v1.5 also changed something with the way it manages connections. I have yet to figure this out, so any input is well received.

**Comment by millin** [comment]
@tomasfarias Hi! Have you had any success with this?

**Comment by satar** [comment]
Just ran into this same issue while trying to get the right combination of MWAA constraints for supporting Airflow 2.5.1 (Airflow 2.6.3 was a bust) with any recent version of dbt-core. I finally was able to get the following combination to at least get past the library constraints NIGHTMARE:
* dbt-core=1.5.0
* airflow-dbt-python[snowflake]==1.0.0
However, when executing a DAG with DbtRunOperator that previously worked with an older "just right" pairing with MWAA running 2.2.2 I got the same import error for UnsetProfileConfig. 

Now the problem is that version dbt-core 1.4.5 and below uses a version of the hologram library that conflicts with the constraints imposed by MWAA with Airflow 2.5.1:
```
ERROR: Cannot install dbt-core because these package versions have conflicting dependencies.

The conflict is caused by:
    hologram 0.0.15 depends on jsonschema<4.0 and >=3.0
    hologram 0.0.14 depends on jsonschema<3.2 and >=3.0
    The user requested (constraint) jsonschema==4.17.3
```
So if we want to continue using airflow-dbt-python, which is a **very** nice to have, we are stuck using Airflow 2.2.2 or possibly look into creating a custom plugin for Apache Airflow PythonVirtualenvOperator.

**Comment by drackham** [comment]
@tomasfarias have you been able to make any progress here?

**Comment by TassOlympus** [comment]
+1

**Comment by millin** [comment]
Hi everyone!
I've spent a few days to ensure compatibility with dbt versions 1.5-1.7. 
I would be glad if someone could test pr #127 and give feedback.

**Comment by tomasfarias** [comment]
Thanks for the work @millin.

Due to the instability that comes with supporting multiple dbt versions, and deprecating Python 3.7, the changes will be available as part of the next major version release (v2.0.0). This release is going out today (already tagged, just waiting for CI).
